# Generated by Django 2.2.2 on 2019-06-26 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjFilial', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('qtdFunc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cnpj_P', models.CharField(default='', max_length=14)),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materia_Prima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mat', models.CharField(default='', max_length=50)),
                ('custo_mat', models.FloatField(default=0.0)),
                ('fornecedor_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 465060, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('areaAtuacao', models.CharField(default='', max_length=20)),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 465060, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('estado_atuacao', models.CharField(default='', max_length=50)),
                ('senha_repr', models.CharField(default='', max_length=16)),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_de_producao', models.FloatField(default=0.0)),
                ('preco_de_venda', models.FloatField(default=0.0)),
                ('nome', models.CharField(default='', max_length=50)),
                ('mat_prima_necessaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Materia_Prima')),
            ],
        ),
        migrations.CreateModel(
            name='Lote_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_produtos', models.IntegerField(default=0)),
                ('data_validade', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 468732, tzinfo=utc), verbose_name='data de validade')),
                ('data_producao', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 468760, tzinfo=utc), verbose_name='data de produção')),
                ('preco_lote', models.FloatField()),
                ('produto_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 465060, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('data_validade', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 465404, tzinfo=utc), verbose_name='data de validade')),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cnpj_P', models.CharField(default='', max_length=14)),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adm_Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 18, 46, 52, 465060, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('senha_adm', models.CharField(default='', max_length=16)),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
