# Generated by Django 2.2.2 on 2019-07-01 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm_Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('cnpj_filial', models.CharField(default='', max_length=14)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 490135, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('senha_adm', models.CharField(default='', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpj_P', models.CharField(default='', max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('cnpj_filial', models.CharField(default='', max_length=14)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 490135, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('data_validade', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 490433, tzinfo=utc), verbose_name='Data de Validade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjFilial', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('qtdFunc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cnpj_P', models.CharField(default='', max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materia_Prima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mat', models.CharField(default='', max_length=50)),
                ('custo_mat', models.FloatField(default=0.0)),
                ('fornecedor_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('cnpj_filial', models.CharField(default='', max_length=14)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 490135, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('estado_atuacao', models.CharField(default='', max_length=50)),
                ('senha_repr', models.CharField(default='', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(default='', max_length=20)),
                ('endereco_P', models.CharField(default='', max_length=100)),
                ('email_P', models.CharField(default='', max_length=50)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('cnpj_filial', models.CharField(default='', max_length=14)),
                ('dataContratacao_Func', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 490135, tzinfo=utc), verbose_name='data de contratação')),
                ('salario_Func', models.FloatField(default=1000.0)),
                ('area_atuacao', models.CharField(default='', max_length=20)),
                ('contrato', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezmanagement.Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_de_producao', models.FloatField(default=0.0)),
                ('preco_de_venda', models.FloatField(default=0.0)),
                ('nome', models.CharField(default='', max_length=50)),
                ('mat_prima_necessaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Materia_Prima')),
            ],
        ),
        migrations.CreateModel(
            name='Lote_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_produtos', models.IntegerField(default=0)),
                ('data_validade', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 493524, tzinfo=utc), verbose_name='data de validade')),
                ('data_producao', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 2, 40, 46, 493546, tzinfo=utc), verbose_name='data de produção')),
                ('preco_lote', models.FloatField()),
                ('produto_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='filial_associada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial'),
        ),
    ]
