# Generated by Django 2.2.2 on 2019-06-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjFilial', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('qtdFunc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_P', models.CharField(default='', max_length=50)),
                ('telefone_P', models.CharField(max_length=20)),
                ('endereco_P', models.CharField(max_length=100)),
                ('email_P', models.CharField(max_length=50)),
                ('cnpjFilial', models.CharField(default='', max_length=14)),
                ('cpf_P', models.CharField(default='', max_length=11)),
                ('dataContratacao_Func', models.DateTimeField(verbose_name='data de contratação')),
                ('salario_Func', models.FloatField()),
                ('filialAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezmanagement.Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adm_Local',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ezmanagement.Funcionario')),
                ('senha_adm', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('ezmanagement.funcionario',),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ezmanagement.Funcionario')),
                ('areaAtuacao', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('ezmanagement.funcionario',),
        ),
    ]
